### ISSUE TITLE
Searchbar: Crashes on special character.

### ISSUE THREAD

**Issue by nklerk** [Shepless/neeo-driver-manager#3]
When entering a "%" character the code crashes. I was looking if i needed to use search operators.

`[1] URIError: Failed to decode param '/api/drivers/%'
[1]     at decodeURIComponent (<anonymous>)
[1]     at decode_param (/home/pi/neeo/manager/client/node_modules/express/lib/router/layer.js:172:12)
[1]     at Layer.match (/home/pi/neeo/manager/client/node_modules/express/lib/router/layer.js:123:27)
[1]     at matchLayer (/home/pi/neeo/manager/client/node_modules/express/lib/router/index.js:574:18)
[1]     at next (/home/pi/neeo/manager/client/node_modules/express/lib/router/index.js:220:15)
[1]     at expressInit (/home/pi/neeo/manager/client/node_modules/express/lib/middleware/init.js:40:5)
[1]     at Layer.handle [as handle_request] (/home/pi/neeo/manager/client/node_modules/express/lib/router/layer.js:95:5)
[1]     at trim_prefix (/home/pi/neeo/manager/client/node_modules/express/lib/router/index.js:317:13)
[1]     at /home/pi/neeo/manager/client/node_modules/express/lib/router/index.js:284:7
[1]     at Function.process_params (/home/pi/neeo/manager/client/node_modules/express/lib/router/index.js:335:12)
`

**Comment by Shepless** [comment]
Is resolved in #7 

Let me know if you have any more issues.
